### ISSUE TITLE
You're not the license granter

### ISSUE THREAD

**Issue by sateffen** [kaoDev/kalleott.de#2]
Hey,

in your [license file](https://github.com/kaoDev/kalleott.de/blob/master/LICENSE#L3) the license granter is not you but [him](https://github.com/resir014). I guess that's due to copy&paste.

I didn't include it in the pull-request, because there might be a reason I don't know, but wanted to tell it.

Cheers

**Comment by kaoDev** [comment]
Yes it probably has its root in a copy paste error, I will change it to the original MIT text
