### ISSUE TITLE
Add rss

### ISSUE THREAD

**Issue by sateffen** [kaoDev/kalleott.de#3]
Hey,

without RSS it's pretty hard to keep track of what's happening on such a website. It would be great to add RSS to make the site trackable.

Cheers

**Comment by kaoDev** [comment]
I'm not using RSS myself, but have just added the rss plugin to generate the rss.xml file, can you have a look if it's working as expected?

**Comment by sateffen** [comment]
Using it with [feedly](https://feedly.com) works like expected. Thank you :)
